In [712]:
# Perfom data manipulation and analysis.
import pandas as pd

# Perfoming mathematical calculations.
import numpy as np

# The two libraries below will aid in creating visualizations.
import matplotlib.pyplot as plt 
import seaborn as sns

In [713]:
# Read the CSV data file
df = pd.read_csv('Data/Marvel Vs DC New.csv', index_col = False)
df

,ID,Movie,Year,Genre,RunTime,Description,IMDB_Score
0,0,Eternals,-2021,"Action,Adventure,Drama",0,"The saga of the Eternals, a race of immortal b...",0.0
1,1,Loki,(2021– ),"Action,Adventure,Fantasy",0,A new Marvel chapter with Loki at its center.,0.0
2,2,The Falcon and the Winter Soldier,-2021,"Action,Adventure,Drama",50 min,"Following the events of 'Avengers: Endgame,' S...",7.5
3,3,WandaVision,-2021,"Action,Comedy,Drama",350 min,Blends the style of classic sitcoms with the M...,8.1
4,4,Spider-Man: No Way Home,-2021,"Action,Adventure,Sci-Fi",0,A continuation of Spider-Man: Far From Home.,0.0
...,...,...,...,...,...,...,...
1685,1685,DC's Legends of Tomorrow,(2016– ),"Action,Adventure,Drama",42 min,"Worlds lived, worlds died. Nothing will ever b...",8.5
1686,1686,Supergirl,(2015–2021),"Action,Adventure,Drama",42 min,"In the wake of Lex Luthor's return, the show f...",8.3
1687,1687,Supergirl,(2015–2021),"Action,Adventure,Drama",42 min,Kara comes face to face with Red Daughter and ...,8.1
1688,1688,Supergirl,(2015–2021),"Action,Adventure,Drama",42 min,Kara and Lena head to Kaznia to hunt down Lex....,7.4
1689,1689,Supergirl,(2015–2021),"Action,Adventure,Drama",42 min,Supergirl must deal with the destructive after...,7.5

## Data Understanding

In [714]:
# make a copy of the dataset for further analysis
entertainment_df = df.copy()
entertainment_df

,ID,Movie,Year,Genre,RunTime,Description,IMDB_Score
0,0,Eternals,-2021,"Action,Adventure,Drama",0,"The saga of the Eternals, a race of immortal b...",0.0
1,1,Loki,(2021– ),"Action,Adventure,Fantasy",0,A new Marvel chapter with Loki at its center.,0.0
2,2,The Falcon and the Winter Soldier,-2021,"Action,Adventure,Drama",50 min,"Following the events of 'Avengers: Endgame,' S...",7.5
3,3,WandaVision,-2021,"Action,Comedy,Drama",350 min,Blends the style of classic sitcoms with the M...,8.1
4,4,Spider-Man: No Way Home,-2021,"Action,Adventure,Sci-Fi",0,A continuation of Spider-Man: Far From Home.,0.0
...,...,...,...,...,...,...,...
1685,1685,DC's Legends of Tomorrow,(2016– ),"Action,Adventure,Drama",42 min,"Worlds lived, worlds died. Nothing will ever b...",8.5
1686,1686,Supergirl,(2015–2021),"Action,Adventure,Drama",42 min,"In the wake of Lex Luthor's return, the show f...",8.3
1687,1687,Supergirl,(2015–2021),"Action,Adventure,Drama",42 min,Kara comes face to face with Red Daughter and ...,8.1
1688,1688,Supergirl,(2015–2021),"Action,Adventure,Drama",42 min,Kara and Lena head to Kaznia to hunt down Lex....,7.4
1689,1689,Supergirl,(2015–2021),"Action,Adventure,Drama",42 min,Supergirl must deal with the destructive after...,7.5

In [715]:
''' Identify if column ID has any important relevance in our dataset .
    It appears it is a repetition of the row index.
    Now we should drop it permanently
'''
entertainment_df['ID'].value_counts()

1689    1
1160    1
1112    1
1114    1
1116    1
       ..
569     1
571     1
573     1
575     1
0       1
Name: ID, Length: 1690, dtype: int64

In [716]:
# Drop column ID
entertainment_df = entertainment_df.drop(columns='ID')
entertainment_df

,Movie,Year,Genre,RunTime,Description,IMDB_Score
0,Eternals,-2021,"Action,Adventure,Drama",0,"The saga of the Eternals, a race of immortal b...",0.0
1,Loki,(2021– ),"Action,Adventure,Fantasy",0,A new Marvel chapter with Loki at its center.,0.0
2,The Falcon and the Winter Soldier,-2021,"Action,Adventure,Drama",50 min,"Following the events of 'Avengers: Endgame,' S...",7.5
3,WandaVision,-2021,"Action,Comedy,Drama",350 min,Blends the style of classic sitcoms with the M...,8.1
4,Spider-Man: No Way Home,-2021,"Action,Adventure,Sci-Fi",0,A continuation of Spider-Man: Far From Home.,0.0
...,...,...,...,...,...,...
1685,DC's Legends of Tomorrow,(2016– ),"Action,Adventure,Drama",42 min,"Worlds lived, worlds died. Nothing will ever b...",8.5
1686,Supergirl,(2015–2021),"Action,Adventure,Drama",42 min,"In the wake of Lex Luthor's return, the show f...",8.3
1687,Supergirl,(2015–2021),"Action,Adventure,Drama",42 min,Kara comes face to face with Red Daughter and ...,8.1
1688,Supergirl,(2015–2021),"Action,Adventure,Drama",42 min,Kara and Lena head to Kaznia to hunt down Lex....,7.4
1689,Supergirl,(2015–2021),"Action,Adventure,Drama",42 min,Supergirl must deal with the destructive after...,7.5

In [717]:
# Understand construction of columns in the dataset
entertainment_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1690 entries, 0 to 1689
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Movie        1690 non-null   object
 1   Year         1657 non-null   object
 2   Genre        1683 non-null   object
 3   RunTime      1690 non-null   object
 4   Description  1690 non-null   object
 5   IMDB_Score   1690 non-null   float64
dtypes: float64(1), object(5)
memory usage: 79.3+ KB

In [718]:
# From the Observation Above:
'''The dataset has a total of 6 columns
   5 columns are of Dtype object -> Movie, Year, Genre, RunTime, Description
   1 column is of Dtype float -> IMDB_SCORE
'''
print(' ')

**NOTE**

Columns to convert from objects to int -> RunTime

Columns to convert from objects to Datetime -> Year

In [719]:
# Clean RunTime column
# Strip additional spaces first before replacing data
entertainment_df['RunTime'] = entertainment_df['RunTime'].str.strip().str.replace(' min', '')
entertainment_df

,Movie,Year,Genre,RunTime,Description,IMDB_Score
0,Eternals,-2021,"Action,Adventure,Drama",0,"The saga of the Eternals, a race of immortal b...",0.0
1,Loki,(2021– ),"Action,Adventure,Fantasy",0,A new Marvel chapter with Loki at its center.,0.0
2,The Falcon and the Winter Soldier,-2021,"Action,Adventure,Drama",50,"Following the events of 'Avengers: Endgame,' S...",7.5
3,WandaVision,-2021,"Action,Comedy,Drama",350,Blends the style of classic sitcoms with the M...,8.1
4,Spider-Man: No Way Home,-2021,"Action,Adventure,Sci-Fi",0,A continuation of Spider-Man: Far From Home.,0.0
...,...,...,...,...,...,...
1685,DC's Legends of Tomorrow,(2016– ),"Action,Adventure,Drama",42,"Worlds lived, worlds died. Nothing will ever b...",8.5
1686,Supergirl,(2015–2021),"Action,Adventure,Drama",42,"In the wake of Lex Luthor's return, the show f...",8.3
1687,Supergirl,(2015–2021),"Action,Adventure,Drama",42,Kara comes face to face with Red Daughter and ...,8.1
1688,Supergirl,(2015–2021),"Action,Adventure,Drama",42,Kara and Lena head to Kaznia to hunt down Lex....,7.4
1689,Supergirl,(2015–2021),"Action,Adventure,Drama",42,Supergirl must deal with the destructive after...,7.5

In [720]:
# convert RunTime column from object to integer type
entertainment_df['RunTime'] = entertainment_df['RunTime'].astype(int)

In [721]:
# Cleaning column Year
entertainment_df['Year']

0             -2021
1          (2021– )
2             -2021
3             -2021
4             -2021
           ...
1685       (2016– )
1686    (2015–2021)
1687    (2015–2021)
1688    (2015–2021)
1689    (2015–2021)
Name: Year, Length: 1690, dtype: object

In [722]:
# Remove parentheses
entertainment_df['Year'] = entertainment_df['Year'].str.replace(r'[()]', '', regex=True)  
entertainment_df['Year']

0           -2021
1          2021–
2           -2021
3           -2021
4           -2021
          ...
1685       2016–
1686    2015–2021
1687    2015–2021
1688    2015–2021
1689    2015–2021
Name: Year, Length: 1690, dtype: object

In [723]:
# Extract individual years and year ranges
entertainment_df['Year'] = entertainment_df['Year'].str.extract(r'(\b\d{4}\b(?:–\d{4})?)')
entertainment_df['Year']

0            2021
1            2021
2            2021
3            2021
4            2021
          ...
1685         2016
1686    2015–2021
1687    2015–2021
1688    2015–2021
1689    2015–2021
Name: Year, Length: 1690, dtype: object

In [724]:
# Separate year ranges into start and end years
entertainment_df['Start Year'] = entertainment_df['Year'].str.extract(r'(\b\d{4}\b)')
entertainment_df['End Year'] = entertainment_df['Year'].str.extract(r'–(\d{4})')

In [725]:
# Avoid dropping of years with nan values
entertainment_df['End Year'] = entertainment_df['End Year'].replace(np.nan, 'not defined')

In [726]:
entertainment_df['Year'].value_counts()

2001–2011    176
2001–2004    120
2014–2019    101
2013–2020     92
2015–2018     91
            ...
2008–2012      1
2004           1
1989           1
1952–1958      1
1990           1
Name: Year, Length: 76, dtype: int64

In [727]:
entertainment_df['Year']

0            2021
1            2021
2            2021
3            2021
4            2021
          ...
1685         2016
1686    2015–2021
1687    2015–2021
1688    2015–2021
1689    2015–2021
Name: Year, Length: 1690, dtype: object

In [728]:
# Statistical information
entertainment_df.describe()

           RunTime   IMDB_Score
count  1690.000000  1690.000000
mean     34.124852     6.877337
std      32.333141     2.690564
min       0.000000     0.000000
25%      21.000000     6.900000
50%      30.000000     7.800000
75%      43.000000     8.400000
max     527.000000     9.600000

## Data Preparation

In [729]:
entertainment_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1690 entries, 0 to 1689
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Movie        1690 non-null   object
 1   Year         1655 non-null   object
 2   Genre        1683 non-null   object
 3   RunTime      1690 non-null   int32
 4   Description  1690 non-null   object
 5   IMDB_Score   1690 non-null   float64
 6   Start Year   1655 non-null   object
 7   End Year     1690 non-null   object
dtypes: float64(1), int32(1), object(6)
memory usage: 99.1+ KB

**Check for null values**

In [730]:
# Find the total number of null values in each column
entertainment_df.isna().sum()

Movie           0
Year           35
Genre           7
RunTime         0
Description     0
IMDB_Score      0
Start Year     35
End Year        0
dtype: int64

In [731]:
entertainment_df

,Movie,Year,Genre,RunTime,Description,IMDB_Score,Start Year,End Year
0,Eternals,2021,"Action,Adventure,Drama",0,"The saga of the Eternals, a race of immortal b...",0.0,2021,not defined
1,Loki,2021,"Action,Adventure,Fantasy",0,A new Marvel chapter with Loki at its center.,0.0,2021,not defined
2,The Falcon and the Winter Soldier,2021,"Action,Adventure,Drama",50,"Following the events of 'Avengers: Endgame,' S...",7.5,2021,not defined
3,WandaVision,2021,"Action,Comedy,Drama",350,Blends the style of classic sitcoms with the M...,8.1,2021,not defined
4,Spider-Man: No Way Home,2021,"Action,Adventure,Sci-Fi",0,A continuation of Spider-Man: Far From Home.,0.0,2021,not defined
...,...,...,...,...,...,...,...,...
1685,DC's Legends of Tomorrow,2016,"Action,Adventure,Drama",42,"Worlds lived, worlds died. Nothing will ever b...",8.5,2016,not defined
1686,Supergirl,2015–2021,"Action,Adventure,Drama",42,"In the wake of Lex Luthor's return, the show f...",8.3,2015,2021
1687,Supergirl,2015–2021,"Action,Adventure,Drama",42,Kara comes face to face with Red Daughter and ...,8.1,2015,2021
1688,Supergirl,2015–2021,"Action,Adventure,Drama",42,Kara and Lena head to Kaznia to hunt down Lex....,7.4,2015,2021
1689,Supergirl,2015–2021,"Action,Adventure,Drama",42,Supergirl must deal with the destructive after...,7.5,2015,2021

In [732]:
entertainment_df = entertainment_df.dropna().reset_index(drop=True)
entertainment_df

,Movie,Year,Genre,RunTime,Description,IMDB_Score,Start Year,End Year
0,Eternals,2021,"Action,Adventure,Drama",0,"The saga of the Eternals, a race of immortal b...",0.0,2021,not defined
1,Loki,2021,"Action,Adventure,Fantasy",0,A new Marvel chapter with Loki at its center.,0.0,2021,not defined
2,The Falcon and the Winter Soldier,2021,"Action,Adventure,Drama",50,"Following the events of 'Avengers: Endgame,' S...",7.5,2021,not defined
3,WandaVision,2021,"Action,Comedy,Drama",350,Blends the style of classic sitcoms with the M...,8.1,2021,not defined
4,Spider-Man: No Way Home,2021,"Action,Adventure,Sci-Fi",0,A continuation of Spider-Man: Far From Home.,0.0,2021,not defined
...,...,...,...,...,...,...,...,...
1643,DC's Legends of Tomorrow,2016,"Action,Adventure,Drama",42,"Worlds lived, worlds died. Nothing will ever b...",8.5,2016,not defined
1644,Supergirl,2015–2021,"Action,Adventure,Drama",42,"In the wake of Lex Luthor's return, the show f...",8.3,2015,2021
1645,Supergirl,2015–2021,"Action,Adventure,Drama",42,Kara comes face to face with Red Daughter and ...,8.1,2015,2021
1646,Supergirl,2015–2021,"Action,Adventure,Drama",42,Kara and Lena head to Kaznia to hunt down Lex....,7.4,2015,2021
1647,Supergirl,2015–2021,"Action,Adventure,Drama",42,Supergirl must deal with the destructive after...,7.5,2015,2021

**Create a custom function for checking the mean, mode and median of dataset column**

In [733]:
# CUSTOM FUNCTION
def m_m_m(col_name, stat_func):
    if stat_func == 'mean':
        col_stat = entertainment_df[col_name].mean()
    elif stat_func == 'median':
        col_stat = entertainment_df[col_name].median()
    elif stat_func == 'mode':
        col_stat = entertainment_df[col_name].mode()[0]  # Get the first mode value
    else:
        raise ValueError("Invalid stat_func. Use 'mean', 'median', or 'mode'.")
    
    return f"{stat_func.capitalize()}: {col_stat}"

In [734]:
# check how many times runtime == 0. 
entertainment_df['RunTime'].value_counts()

22     272
42     257
0      243
43     220
44      71
      ...
99       1
101      1
103      1
104      1
73       1
Name: RunTime, Length: 126, dtype: int64

In [735]:
m_m_m('RunTime', 'mode')

'Mode: 22'

In [736]:
m_m_m('RunTime', 'mean')

'Mean: 34.88531553398058'

In [737]:
m_m_m('RunTime', 'median')

'Median: 41.0'

In [ ]:
# Replace the movies with 0 RunTime to be NaN
entertainment_df['RunTime'] = entertainment_df['RunTime'].replace(0, round(entertainment_df['RunTime'].mean(),0))

In [739]:
entertainment_df['RunTime'].value_counts()

22     272
42     257
35     244
43     220
44      71
      ...
99       1
101      1
103      1
104      1
74       1
Name: RunTime, Length: 125, dtype: int64

In [740]:
entertainment_df

,Movie,Year,Genre,RunTime,Description,IMDB_Score,Start Year,End Year
0,Eternals,2021,"Action,Adventure,Drama",35,"The saga of the Eternals, a race of immortal b...",0.0,2021,not defined
1,Loki,2021,"Action,Adventure,Fantasy",35,A new Marvel chapter with Loki at its center.,0.0,2021,not defined
2,The Falcon and the Winter Soldier,2021,"Action,Adventure,Drama",50,"Following the events of 'Avengers: Endgame,' S...",7.5,2021,not defined
3,WandaVision,2021,"Action,Comedy,Drama",350,Blends the style of classic sitcoms with the M...,8.1,2021,not defined
4,Spider-Man: No Way Home,2021,"Action,Adventure,Sci-Fi",35,A continuation of Spider-Man: Far From Home.,0.0,2021,not defined
...,...,...,...,...,...,...,...,...
1643,DC's Legends of Tomorrow,2016,"Action,Adventure,Drama",42,"Worlds lived, worlds died. Nothing will ever b...",8.5,2016,not defined
1644,Supergirl,2015–2021,"Action,Adventure,Drama",42,"In the wake of Lex Luthor's return, the show f...",8.3,2015,2021
1645,Supergirl,2015–2021,"Action,Adventure,Drama",42,Kara comes face to face with Red Daughter and ...,8.1,2015,2021
1646,Supergirl,2015–2021,"Action,Adventure,Drama",42,Kara and Lena head to Kaznia to hunt down Lex....,7.4,2015,2021
1647,Supergirl,2015–2021,"Action,Adventure,Drama",42,Supergirl must deal with the destructive after...,7.5,2015,2021

*It appears the values that had NaN values On RunTime also has 0 values on IMDB_Score

In [741]:
# check how many times IMDB_Score == 0. 
entertainment_df['IMDB_Score'].value_counts()

0.0    165
8.1     86
8.2     82
8.6     79
8.0     76
8.4     72
7.9     70
7.8     64
8.5     62
8.3     62
7.7     61
7.4     51
7.5     50
7.6     49
8.7     49
7.3     46
8.8     41
7.0     40
7.2     39
9.0     38
9.1     37
6.9     30
7.1     29
6.8     26
8.9     23
9.2     23
6.5     22
6.4     17
6.7     15
6.1     15
6.2     14
9.3     13
6.0     12
6.6     10
6.3     10
5.7      9
5.9      9
5.6      9
9.5      8
5.5      6
5.4      5
9.4      4
5.0      3
5.8      3
9.6      3
5.2      2
3.5      1
3.8      1
4.0      1
1.1      1
4.9      1
4.4      1
4.7      1
3.4      1
5.1      1
Name: IMDB_Score, dtype: int64

In [742]:
m_m_m('IMDB_Score', 'mode')

'Mode: 0.0'

In [743]:
m_m_m('IMDB_Score', 'mean')

'Mean: 7.042050970873786'

In [744]:
m_m_m('IMDB_Score', 'median')

'Median: 7.9'

In [745]:
# Replace the movies with 0 IMDB_Score to be NaN
entertainment_df['IMDB_Score'] = entertainment_df['IMDB_Score'].replace(0, round(entertainment_df['IMDB_Score'].mean(),1))

In [746]:
entertainment_df

,Movie,Year,Genre,RunTime,Description,IMDB_Score,Start Year,End Year
0,Eternals,2021,"Action,Adventure,Drama",35,"The saga of the Eternals, a race of immortal b...",7.0,2021,not defined
1,Loki,2021,"Action,Adventure,Fantasy",35,A new Marvel chapter with Loki at its center.,7.0,2021,not defined
2,The Falcon and the Winter Soldier,2021,"Action,Adventure,Drama",50,"Following the events of 'Avengers: Endgame,' S...",7.5,2021,not defined
3,WandaVision,2021,"Action,Comedy,Drama",350,Blends the style of classic sitcoms with the M...,8.1,2021,not defined
4,Spider-Man: No Way Home,2021,"Action,Adventure,Sci-Fi",35,A continuation of Spider-Man: Far From Home.,7.0,2021,not defined
...,...,...,...,...,...,...,...,...
1643,DC's Legends of Tomorrow,2016,"Action,Adventure,Drama",42,"Worlds lived, worlds died. Nothing will ever b...",8.5,2016,not defined
1644,Supergirl,2015–2021,"Action,Adventure,Drama",42,"In the wake of Lex Luthor's return, the show f...",8.3,2015,2021
1645,Supergirl,2015–2021,"Action,Adventure,Drama",42,Kara comes face to face with Red Daughter and ...,8.1,2015,2021
1646,Supergirl,2015–2021,"Action,Adventure,Drama",42,Kara and Lena head to Kaznia to hunt down Lex....,7.4,2015,2021
1647,Supergirl,2015–2021,"Action,Adventure,Drama",42,Supergirl must deal with the destructive after...,7.5,2015,2021

In [751]:
# check the statistical analysis again
entertainment_df.describe()

           RunTime   IMDB_Score
count  1648.000000  1648.000000
mean     40.046117     7.742900
std      28.846899     0.902078
min       1.000000     1.100000
25%      22.000000     7.000000
50%      41.000000     7.900000
75%      43.000000     8.400000
max     527.000000     9.600000